---
title: "property_verification_EEG_4"
author: "Harshada Vinaya"
date: "2024-11-18"
output: html_document
---

# Loading the libraries 
library (lme4)
library(sjPlot)
library(lmerTest)
library(car)
library(tidyverse)

# Import 100 ms averaged single trial EEG data for all property trials
data_300_400 <- read_csv("../data/prop_ms_300_400.csv")

# Ensure the correct file
colnames(data_300_400)

# Z-scoring all of the predictors for the entire dataset
data_300_400$word_freq_zscore <- scale(data_300_400$prop_Lg10WF)
data_300_400$glove_zscore <- scale(data_300_400$glove_distance)
data_300_400$smn_zscore <- scale(data_300_400$sensorimotor_distance)


# Checking
range(data_300_400$word_freq_zscore)
range(data_300_400$glove_zscore)
range(data_300_400$smn_zscore)

# Divide TRUE and FALSE trials
data_300_400_PT <- data_300_400[data_300_400$veracity == TRUE, ]
data_300_400_PF <- data_300_400[data_300_400$veracity == FALSE, ]

print(nrow(data_300_400_PT))
print(nrow(data_300_400_PF))

###########################################################################

# Model Fitting for TRUE properties #

# Frequency model

f_pt_40 <- lmer(voltage ~ (word_freq_zscore)*(X + Y + Z) 
                + (1 | subject) 
                + (1 | property), 
                data_300_400_PT, REML = FALSE)

# Summary of the Frequency model 
summary(f_pt_40)

#Distributional model

d_pt_40 <- lmer(voltage ~ (word_freq_zscore + glove_zscore)*(X + Y + Z) 
                + (1 | subject) 
                + (1 | property), 
                data_300_400_PT, REML = FALSE)

# Summary of the Distributional model
summary(d_pt_40)


# Sensorimotor model

s_pt_40 <- lmer(voltage ~ (word_freq_zscore + smn_zscore)*(X + Y + Z) 
                + (1 | subject) 
                + (1 | property), 
                data_300_400_PT, REML = FALSE)

# Summary of the Sensorimotor model
summary(s_pt_40)

# Distributional and Sensorimotor (combined) model

ds_pt_40 <- lmer(voltage ~ (word_freq_zscore + 
                              glove_zscore + 
                              smn_zscore)*(X + Y + Z) 
                 + (1 | subject) 
                 + (1 | property), 
                 data_300_400_PT, REML = FALSE)

# Summary of the combined model
summary(ds_pt_40)


###############################################################

# Saving TRUE property AIC results

x_pt_40 <- c('f PT AIC', 'd PT AIC', 's PT AIC','ds PT AIC')
y_pt_40 <- c(AIC(f_pt_40), AIC(d_pt_40), AIC(s_pt_40), AIC(ds_pt_40))
aic_pt_40 <- data.frame(x_pt_40, y_pt_40)
write.csv(aic_pt_40, "aic_pt_40")

############################################################################

# Model Fitting for FALSE properties

# Frequency model

f_pf_40 <- lmer(voltage ~ (word_freq_zscore)*(X + Y + Z) 
                + (1 | subject) 
                + (1 | property), 
                data_300_400_PF, REML = FALSE)

# Summary of F model
summary(f_pf_40)


# Distribution model

d_pf_40 <- lmer(voltage ~ (word_freq_zscore+ glove_zscore)*(X + Y + Z) 
                + (1 | subject) 
                + (1 | property), 
                data_300_400_PF, REML = FALSE)

# Summary of D model
summary(d_pf_40)


# Sensorimotor model

s_pf_40 <- lmer(voltage ~ (word_freq_zscore + smn_zscore)*(X + Y + Z) 
                + (1 | subject) 
                + (1 | property), 
                data_300_400_PF, REML = FALSE)

# Summary of S model
summary(s_pf_40)


# Combined model

ds_pf_40 <- lmer(voltage ~ (word_freq_zscore +
                              glove_zscore + 
                              smn_zscore)*(X + Y + Z) 
                 + (1 | subject) 
                 + (1 | property), 
                 data_300_400_PF, REML = FALSE)

# Summary of DS model
summary(ds_pf_40)

# Saving FALSE property AIC results

x_pf_40 <- c('f PF AIC', 'd PF AIC', 's PF AIC','ds PF AIC')
y_pf_40 <- c(AIC(f_pf_40), AIC(d_pf_40), AIC(s_pf_40), AIC(ds_pf_40))
aic_pf_40 <- data.frame(x_pf_40, y_pf_40)
write.csv(aic_pf_40, "aic_pf_40")
